### ISSUE TITLE
what is 'keyword_POS' and 'keyword_NER' in Copy_Copy_updated_COVID19_devdata_Apr25_2020.csv

### ISSUE THREAD

**Issue by BoonthichaSaejia** [VincentK1991/BERT_summarization_1#4]
I tried to guess what did you process to get these 2 columns but without the full csv, it is hard. Would you mind explain about it, so i could know how to create the input for preprocessing.py

**Comment by VincentK1991** [comment]
Sorry, I just realized the notebook was incomplete and I totally forget to update this part of the notebooks. I just re-organized the notebooks. this should be clearer now I hope.
